version: "3"
services:
    web:
        build: ./api
        ports:
            - "8080:8080"
        depends_on:
            - db
    fed:
        build: ./frontend
        ports:
            - "3000:3000"
    db:
        build: ./postgresql
        ports:
            - "5432:5432"

