---

- name: Create our image
  hosts: localhost
  tasks:

    - docker_service:
        project_name: fmp
        definition:
            version: "3"
            services:
                web:
                    build: "{{ playbook_dir }}/api"
                    ports:
                        - "8080:8080"
                    depends_on:
                        - db
                fed:
                    build: "{{ playbook_dir }}/frontend"
                    ports:
                        - "3000:3000"
                db:
                    build: "{{ playbook_dir }}/postgresql"
                    ports:
                        - "5432:5432"

