---
# tasks file for node-role

# - name: add apt key for nodesource
#   apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

# - name: add repo for nodesource
#   apt_repository:
#     repo: 'deb https://deb.nodesource.com/node_0.10{{ ansible_distribution_release }}main' 
#     update_cache: yes

# - name: install nodejs
#   apt: name=nodejs

# - name: install nodejs
#   apt: name=npm

- name: Download foo.conf
  get_url:
    url: https://deb.nodesource.com/setup_10.x
    dest: /home/setup_10.sh
    mode: 0777
    validate_certs: false
    

- name: Run a script with arguments
  command: sh /home/setup_10.sh


- name: install nodejs
  apt: name=nodejs

# - name: install npm
#   apt: name=npm