version: '2'
services:
  jenkins:
    image: 'jenkinsci/blueocean'
    hostname: jenkins
    user: root
    labels:
      kompose.service.type: nodeport
    ports:
      - '8080:8080'
      - '8443:8443'
      - '50000:50000'
    volumes:
      - './jenkins_data:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - jenkinsnet

  sonarqube:
    image: sonarqube
    hostname: sonarqube
    ports:
      - "9000:9000"
    networks:
      jenkinsnet:
        # ipv4_address: 172.29.0.10
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres
    hostname: db
    networks:
      - jenkinsnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data


volumes:
  jenkins_data:
    driver: local

  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:

networks:

  jenkinsnet:
    # driver: bridge

    external:
      name: jenkinsnet


