version: "3"
services: 
        web:
            build: .
            ports:
                - "8080:8080"
            depends_on:
                - db
            command: npm run build
            command: npm start
            command: npm run client

        db:
            image: mongo
            ports:
                - "27017:27017"
